### ISSUE TITLE
Access the Android WebView Settings

### ISSUE THREAD

**Issue by DATL4G** [KevinnZou/compose-webview-multiplatform#2]
First of all thanks for providing this library.

I need to access the android WebView settings, could you please provide an option to do this.
Maybe a method/value that returns a generic in common, then we can parse it ourself in the specific targets.
I have to change some attributes and apply the settings to the webview again.

### Additional information for Desktop

People need to add the JavaFx modules themself, because your lib doesn't provide native packages.
Maybe you can extend the build.gradle.kts usage guide.

I did it like this, (a bit overkill but I need this configuration for something else) just strip it down or something:

```kotlin
val javafx = CompileOptions.jvmTarget // jvmTarget set for the whole project
val javafxModules = listOf(
    "javafx.base",
    "javafx.graphics", // depends on base
    "javafx.controls", // depends on base & graphics
    "javafx.media", // depends on base & graphics
    "javafx.swing", // depends on base & graphics
    "javafx.web", // depends on base & graphics & controls & media
)

kotlin {
	...
	jvm("desktop")
	
	sourceSets {
		...
		val desktopMain by getting {
			dependencies {
				...
				val javaFxSuffix = getJavaFxSuffix()
                javafxModules.forEach { artifact ->
                    implementation(javaFxLib(artifact, javafx, javaFxSuffix))
                }
			}
		}
	}
}

fun getHost(): Host {
    return when (osdetector.os) {
        "linux" -> Host.Linux
        "osx" -> Host.MAC
        "windows" -> Host.Windows
        else -> {
            val hostOs = System.getProperty("os.name")
            val isMingwX64 = hostOs.startsWith("Windows")

            when {
                hostOs == "Linux" -> Host.Linux
                hostOs == "Mac OS X" -> Host.MAC
                isMingwX64 -> Host.Windows
                else -> throw IllegalStateException("Unknown OS: ${osdetector.classifier}")
            }
        }
    }
}

fun getJavaFxSuffix(): String {
    return when (osdetector.classifier) {
        "linux-x86_64" -> "linux"
        "linux-aarch_64" -> "linux-aarch64"
        "windows-x86_64" -> "win"
        "osx-x86_64" -> "mac"
        "osx-aarch_64" -> "mac-aarch64"
        else -> getHost().label
    }
}

fun javaFxLib(artifactId: String, version: String, suffix: String): String {
    return "org.openjfx:${artifactId.replace('.', '-')}:${version}:${suffix}"
}

enum class Host(val label: String) {
    Linux("linux"),
    Windows("win"),
    MAC("mac");
}
```

**Comment by KevinnZou** [comment]
Thank you for your suggestions! I greatly appreciate your willingness to provide your code as a reference for issues related to the Desktop module. I will make the necessary fixes promptly. Regarding WebView settings, could you provide some specific examples of the settings you require? I am currently in the process of enhancing the common level with additional features, but it is crucial that these features are compatible across all platforms. If the settings are only applicable to Android targets, it would not be appropriate to include them at the common level. However, I hope that you can provide me with more specific examples so that we can work towards finding a suitable solution. Once again, thank you for your help!

**Comment by DATL4G** [comment]
I want to change some settings regarding the dark mode like [`setForceDark`](https://developer.android.com/reference/androidx/webkit/WebSettingsCompat#setForceDark(android.webkit.WebSettings,int)), [`setForceDarkStrategy`](https://developer.android.com/reference/androidx/webkit/WebSettingsCompat#setForceDarkStrategy(android.webkit.WebSettings,int)) etc and change [`setSafeBrowsingEnabled`](https://developer.android.com/reference/androidx/webkit/WebSettingsCompat#setSafeBrowsingEnabled(android.webkit.WebSettings,boolean))

**Comment by KevinnZou** [comment]
I got you. I can add them but I am considering whether they should be added. Since these functions are Android-specific, other platforms do not have similar features. One way to do that is to provide the methods in the shared interface and just implement them in the Android platform. For other platforms, the method calls just do nothing. Do you have any other better suggestions?

**Comment by KevinnZou** [comment]
By the way, for your suggestions about the Desktop module, I think I already included the JavaFX modules in the Desktop module. Do you mean the projects that import my library still need to add modules by themselves? If so, that is what it is designed to be. The reason behind the need for users to manually include the JavaFX modules is due to my use of the "implementation" keyword for importing the modules, instead of "api". This approach was implemented with the aim of optimizing package size. Moreover, I believe it is unnecessary to export the JavaFX modules, as the majority of users simply require the WebView functionality in the common module and do not need to concern themselves with the specific implementation details for each target platform. Could you come up with other more common scenarios in which developers need to have JavaFX modules imported with my library?

**Comment by DATL4G** [comment]
## Regarding the Android Settings

I think that's the best way, maybe you could split platform-specific methods in separate classes.

Like this:

```kotlin
// probably calling on the state I guess, so
val state = rememberWebViewState()

state.enableJavascript(true) // common, can be called on all platforms
state.android.setSafeBrowsingEnabled(false) // can be called from common, but only working on android
```

## Desktop JavaFX

Yes I know the reason behind that, however people importing your library **AND** using the WebView in common code need to add the JavaFX modules to their Desktop module.
If they don't add these, the app won't start because of `java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found`

I don't know if it helps to `api` them, since the JavaFX modules depend on native packages and I can't tell if the native packages will be (down)loaded by doing this or not.

### Other problem

When I add the library to my app, the app may not start (randomly).
First time running works but if I build and run it a second or third time it may or may not start.

Idk the reason behind that, there is no error stacktrace or something.

I have another app which implements this JavaFX WebView itself (since the library didn't exists back then) and I don't have this starting problem.

**Comment by KevinnZou** [comment]
**Regarding the Android Settings**

It is a really great idea to split platform-specific methods into separate classes, I really appreciate it. I will add the necessary functionalities soon!

**Regarding the Desktop JavaFX and Other problem**

I am wondering which desktop platforms are you testing on. Windows or Linux or Mac? I personally tested on Mac Mini using the basic [Compose Multiplatform template](https://github.com/JetBrains/compose-multiplatform-template) and directly imported my library for testing without any issues. There is no need to additionally import JavaFX libraries in the desktop module.

Also, for other problem, I tested with the app built by template multiple times and found no issues. 

I just released the 1.1.0 version today which fixed some bugs. They should not affect the problems mentioned above but please have a try with it and please let me know if the problems still exist!

**Comment by DATL4G** [comment]
## Information
**Operating-System:** Fedora Linux 38
**GNOME-Version:** 44.5
**WindowManager:** X11
**Library Version:** 1.1.0
**Used JDK:** 17 (temurin)

When I don't include the JavaFX modules myself:

<details>
<summary>Full Stacktrace</summary>

```gradle
Sept. 19, 2023 4:29:07 PM com.sun.javafx.application.PlatformImpl startup
WARNUNG: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @2c4d0347'
Graphics Device initialization failed for :  es2, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:283)
	at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:254)
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:264)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:291)
	at javafx.application.Platform.startup(Platform.java:113)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at kotlinx.coroutines.javafx.PlatformInitializer.<clinit>(JavaFxDispatcher.kt:132)
	at kotlinx.coroutines.javafx.JavaFxDispatcherKt.initPlatform(JavaFxDispatcher.kt:115)
	at kotlinx.coroutines.javafx.JavaFx.<clinit>(JavaFxDispatcher.kt:77)
	at kotlinx.coroutines.javafx.JavaFxDispatcherFactory.createDispatcher(JavaFxDispatcher.kt:56)
	at kotlinx.coroutines.internal.MainDispatchersKt.tryCreateDispatcher(MainDispatchers.kt:57)
	at kotlinx.coroutines.internal.MainDispatcherLoader.loadMainDispatcher(MainDispatchers.kt:38)
	at kotlinx.coroutines.internal.MainDispatcherLoader.<clinit>(MainDispatchers.kt:22)
	at kotlinx.coroutines.Dispatchers.getMain(Dispatchers.kt:24)
	at dev.datlag.esports.prodigy.common.PlatformExtendCoroutineKt.getDeviceMain(PlatformExtendCoroutine.kt:8)
	at dev.datlag.esports.prodigy.common.ExtendCoroutineKt.mainDispatcher(ExtendCoroutine.kt:32)
	at dev.datlag.esports.prodigy.common.ExtendCoroutineKt.withMainContext(ExtendCoroutine.kt:66)
	at dev.datlag.esports.prodigy.AppIO$loadAppIcon$1.invokeSuspend(AppIO.kt:39)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:95)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found

Exception in thread "DefaultDispatcher-worker-8" java.lang.IllegalStateException: Module with the Main dispatcher had failed to initialize
	at kotlinx.coroutines.internal.MissingMainCoroutineDispatcher.missing(MainDispatchers.kt:115)
	at kotlinx.coroutines.internal.MissingMainCoroutineDispatcher.isDispatchNeeded(MainDispatchers.kt:96)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:319)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:172)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at dev.datlag.esports.prodigy.common.ExtendCoroutineKt.withMainContext(ExtendCoroutine.kt:66)
	at dev.datlag.esports.prodigy.AppIO$loadAppIcon$1.invokeSuspend(AppIO.kt:39)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.awt.ComposeBridge$coroutineExceptionHandler$1@54b6894a, androidx.compose.runtime.BroadcastFrameClock@5117b62e, StandaloneCoroutine{Cancelling}@677e1da0, Dispatchers.IO]
Caused by: java.lang.ExceptionInInitializerError
	at kotlinx.coroutines.javafx.JavaFxDispatcherKt.initPlatform(JavaFxDispatcher.kt:115)
	at kotlinx.coroutines.javafx.JavaFx.<clinit>(JavaFxDispatcher.kt:77)
	at kotlinx.coroutines.javafx.JavaFxDispatcherFactory.createDispatcher(JavaFxDispatcher.kt:56)
	at kotlinx.coroutines.internal.MainDispatchersKt.tryCreateDispatcher(MainDispatchers.kt:57)
	at kotlinx.coroutines.internal.MainDispatcherLoader.loadMainDispatcher(MainDispatchers.kt:38)
	at kotlinx.coroutines.internal.MainDispatcherLoader.<clinit>(MainDispatchers.kt:22)
	at kotlinx.coroutines.Dispatchers.getMain(Dispatchers.kt:24)
	at dev.datlag.esports.prodigy.common.PlatformExtendCoroutineKt.getDeviceMain(PlatformExtendCoroutine.kt:8)
	at dev.datlag.esports.prodigy.common.ExtendCoroutineKt.mainDispatcher(ExtendCoroutine.kt:32)
	... 10 more
Caused by: java.lang.RuntimeException: No toolkit found
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:276)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:291)
	at javafx.application.Platform.startup(Platform.java:113)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at kotlinx.coroutines.javafx.PlatformInitializer.<clinit>(JavaFxDispatcher.kt:132)
	... 19 more
Caused by: java.lang.ExceptionInInitializerError

Caused by: java.lang.RuntimeException: No toolkit found
```

</details>

After adding the JavaFX modules:

Starts sometimes, sometimes not.
Either way it's always the same stacktrace:

```gradle
Sept. 19, 2023 4:37:24 PM com.sun.javafx.application.PlatformImpl startup
WARNUNG: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @2c4d0347'
```

Here is my repo so you can test around a bit if you want.

https://github.com/DatL4g/eSports-Prodigy

**Comment by DATL4G** [comment]
Using Zulu JDK+FX get's rid of the warning message

> Sept. 19, 2023 4:37:24 PM com.sun.javafx.application.PlatformImpl startup
WARNUNG: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @2c4d0347'

But I still have problems to start the app

**Comment by KevinnZou** [comment]
Hi, I am focusing on solving the WebView Settings issue yesterday. I already added the basic web setting supports like JavaScript and safe browsing, and I will release them in the next version. Since it can only be done case by case, you can submit PR directly if you want some settings and it is not supported by this library.

**Regarding Desktop Issue**

I really appreciate your time and effort in addressing the bugs related to JavaFX. Since I am an Android developer, I am not very familiar with desktop development. In fact, this is my first attempt at desktop development. I chose to use JavaFX for implementing a WebView on the desktop simply because it was the top result in my Google search. Therefore, if you think the CEF Browser is a better option, feel free to go ahead with it. It would be great if you could share your code and submit the PR directly. 

I apologize for the delayed response as I still need to do the job from my company during the daytime.

**Comment by KevinnZou** [comment]
This issue has been solved in the latest version. 
https://github.com/KevinnZou/compose-webview-multiplatform/releases/tag/1.3.0
